### PR TITLE
CI job that runs main tests on CPython debug build

### PR DESCRIPTION
**Pull request by steve-s**

### CODE REVIEW

**Comment by hodgestar** [comment]
Some notes on build times:
* This adds a 5m 30s build step, but many build steps are run in parallel, so the effect on the overall time looks negligible.
* The total build time is largely equal to the build time of the Valgrind step.

**Review by hodgestar — APPROVED** [review]
Looks good. Thanks!

**Comment by steve-s** [comment]
I am not sure that it did what it should have, because the tests passed. I'll play with this PR a bit to find out what's going on.

**Comment by steve-s** [comment]
I am convinced now that HPy was built and the tests have been executed on debug build of CPython, but with this approach we can cover only the CPython version that is the default in Ubuntu, which is at this point `3.8`, which happens to not trigger issue #255 that triggered this exercise. 

Alternative would be to use 3rd party action: https://github.com/deadsnakes/action. I would be up for giving it a go. Are there any issues we see with using 3rd party GitHub action?

**Comment by mattip** [comment]
Using the deadsnakes action sounds reasonable.

**Comment by steve-s** [comment]
Ok, so now we get the expected error. It happens on 3.7 and 3.9 and weirdly not on 3.8.

On unrelated note: when looking at the logs I think I may found out why Windows builds are slower: it uses `pytest-forked` on POSIX systems, but not on Windows (no forking there), so there the tests do not run in parallel.

**Comment by steve-s** [comment]
I rebased the PR on master and added logic to skip the failing tests if debug build of CPython is detected.

**Review by hodgestar — APPROVED** [review]
Happy for this to be merged as soon as the CI run finishes successfully.

I was going to suggest adding an `is_debug_build` helper, but since these checks should all be removed eventually, let's not add a helper that we don't have a long term use case for.

**Pull request merged**
