### PR TITLE
MAINT: fix docs/examples for newer API

### PR DESCRIPTION
**Pull request by mattip**
It seems the `docs/examples/simple.c` got left behind in refactoring. Should building this be part of a CI run?

### CODE REVIEW

**Comment by mattip** [comment]
Is it normal for the windows CI job to fail?

**Review by hodgestar — APPROVED** [review]

**Comment by hodgestar** [comment]
> Is it normal for the windows CI job to fail?

The Windows CI job should and was parsing. The error is a cache miss:
```
There is a cache miss.
tar: could not chdir to 'D:\a\1\.pip'
```
So it's not directly related to HPy code, but to the CI job. I don't know why it failed now though. I suggest we merge this PR and solve this cache error separately.

**Comment by mattip** [comment]
Windows is still failing.

**Comment by mattip** [comment]
rebasing off master fixed the CI failures. @antocuni @rlamy could you take a look?

**Comment by mattip** [comment]
Is this needed for 0.0.2?

**Comment by antocuni** [comment]
@mattip sorry for the late response, I didn't see the notifications.
Thanks for the fix. Indeed, it would be nice if this code were automatically checked by CI.

Merging it now.

**Pull request merged**
