### PR TITLE
Add CPlusPlus support

### PR DESCRIPTION
**Pull request by mattip**
The codebase did not support compiling with a c++ compiler. I also added a CI run for g++

### CODE REVIEW

**Comment by mattip** [comment]
Closes #318. In order to do this the PR:
- Adds a CI run using g++ for tests on ubuntu
- Allows overriding gcc in the `test/Makefile`
- Moves `HPyTuple_Pack` from a macro to an function in `inline_helpers.h`
- Adds guards when exporting functions to prevent mangling the names
- Casts `malloc` (and friends) results to the proper pointer type
- Fixes tests to run with C++
  - Casts where needed
  - Move code so variable declarations are not between a `goto xxx` and the `xxx` label
  - Reorder `HPyType_Spec` initializations so that the order matches the struct definition

The new CI run is passing.

**Review by steve-s — APPROVED** [review]

**Comment by mattip** [comment]
Would anyone else like to review or can this be merged?

**Review by qunaibit — APPROVED** [review]
LGTM

**Comment by mattip** [comment]
ping

**Comment by mattip** [comment]
This PR has two approvals, can we merge it?

**Review by thedrow — APPROVED** [review]

**Comment by mattip** [comment]
:rocket:

**Pull request merged**
