### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
As suggested at https://github.com/hpyproject/hpy/wiki/dev-call-20201105#topics-deferred-to-the-next-dev-call

[Ruff](https://beta.ruff.rs/) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) including bandit, isort, pylint, pyupgrade, and flake8 plus its plugins, and is written in Rust for speed.

The `ruff` Action uses minimal steps to run in ~10 seconds, rapidly providing intuitive GitHub Annotations to contributors.

image

Python file edits were done with:
% [`ruff --select=E703,E711,E712,F841 --fix .`](https://beta.ruff.rs/docs/rules/#error-e)

### CODE REVIEW

**Review by fangerer — APPROVED** [review]
LGTM. Thank you, @cclauss.

**Review by fangerer — CHANGES_REQUESTED** [review]
Sorry, I was a bit too fast in approving. I had some discussion with other HPy devs and they convinced me that can be helpful but we need to carefully select the rules.
Let's wait for some other opinions.

**Comment by hodgestar** [comment]
Given that no big changes were required for the current set of rules to pass, I'm happy with the PR as is. I'm also happy with slightly more relaxed rules though.

**Comment by mattip** [comment]
I think we should reject this PR. The only time code formatting has become a discussion topic is when use of a tool to format code is proposed. This seems to be the flip side of the "code formatters __prevent__ discussions around formatting": to become "code formatters __generate__ unhelpful and long discussions around code formatting".

**Pull request closed without merging**
