### PR TITLE
Rename HPyContext to HPyContext*

### PR DESCRIPTION
**Pull request by hodgestar**
Addresses #150.

### CODE REVIEW

**Comment by hodgestar** [comment]
I'm not sure how reviewable this is, but it's ready for review.

**Comment by hodgestar** [comment]
Once this lands I will attempt to merge it into #125 and #176 to save others some possibly painful merging.

**Review by fangerer — APPROVED** [review]
I didn't review every single line but I did some sampling :-)

**Comment by hodgestar** [comment]
@fangerer Thanks! I am going to merge.

**Comment by antocuni** [comment]
thank you! I also didn't review it in detail but it looks good.
I suppose we also need to fix piconumpy, ultrajson and numpy now

**Comment by hodgestar** [comment]
> thank you! I also didn't review it in detail but it looks good.
> I suppose we also need to fix piconumpy, ultrajson and numpy now

Indeed, there is a bunch of mopping up to do. I can start with ultrajson.

**Comment by hodgestar** [comment]
HPy branches have been updated.

I have opened a pull request to update ultrajson-hpy: https://github.com/hpyproject/ultrajson-hpy/pull/5

**Comment by hodgestar** [comment]
And I've created a pull request for updating piconumpy: https://github.com/paugier/piconumpy/pull/4

**Pull request merged**
