### PR TITLE
Add a microbenchmark

### PR DESCRIPTION
**Pull request by antocuni**
Apparently this branch has been pending for more than 1 year, let's just commit it.

### CODE REVIEW

**Review by hodgestar — APPROVED** [review]
Looks good!

**Comment by hodgestar** [comment]
@antocuni @timfel Should we run the benchmarks all again and make a new benchmark blog post?

**Comment by antocuni** [comment]
> @antocuni @timfel Should we run the benchmarks all again and make a new benchmark blog post?

maybe, but note that these are microbenchmarks, so probably not very interesting for a blog post

**Comment by hodgestar** [comment]
Well, the microbenchmarks do at least show that we didn't mess up some small subset of things too badly.

**Pull request merged**
