### PR TITLE
Test upgrade to macos-12.

### PR DESCRIPTION
**Pull request by fangerer**
**DO NOT MERGE**

According to [this GitHub announcenment](https://github.com/actions/runner-images/issues/6384), `macos-latest` will switch to MacOS 12 (Monterey) next year. I just want to test if we run into problems.

### CODE REVIEW

**Comment by cclauss** [comment]
This pull request has been open for more than a year.  Please rebase and resolve git conflicts.

**Comment by mattip** [comment]
Closing. This was just a test, and is not needed anymore.

**Comment by fangerer** [comment]
> Closing. This was just a test, and is not needed anymore.

I never found the time for further investigations but afaik, our `test_distutils` still fails on `macos-12`. As a workaround, we still use `macos-11`. But yes, we can close this PR for now.

**Comment by cclauss** [comment]
The URL above says `macos-latest` is 12 and 13 is in beta but GitHub Actions hardware is still legacy Intel and not yet Apple Silicon.

**Comment by cclauss** [comment]
@fangerer You are correct.  Still fails…
* #467

**Pull request closed without merging**
