### PR TITLE
Check the source code using CPPCheck

### PR DESCRIPTION
**Pull request by thedrow**
Since this project is written in C, we should use a linter to ensure we don't have issues which will bite us later.
This PR runs cppcheck on the source code and reports the errors back.

We could invest time in the tool's configuration to enforce our own rules, if we so desire.

### CODE REVIEW

**Comment by thedrow** [comment]
The CPPCheck version Ubuntu supplies is rather old.
I'll install it from a different source.

**Comment by thedrow** [comment]
Now the output makes sense.

We have one error which I already fixed in #73.
Some style issues we need to decide what we're going to do with and some unused definitions we can instruct cppcheck to ignore if we need to.

**Comment by antocuni** [comment]
Good idea, thank you!
I have two minor requests:
1. my experience with linters is whenever a new version is released, new warnings/errors begins to pop. Would it be possible to pin cppcheck to a specific version?

2. I would like to have a `make cppcheck` target which contains all the needed options, instead of passing a zillion of options from `azure-pipelines.yml`: it makes it much easier to run the linter locally if you want to.

Moreover, you should probably rebase/merge on top of the current master: now that #73 has been merged, the check should pass.

**Comment by thedrow** [comment]
I did the best I could.

I had to create a Python script since `make` refused to run that bash command to find the Python include path in any other way.
Feel free to improve on that.

In addition, there's no way to install a specific version from snap but I pinned ourselves to a specific channel.

> Good idea, thank you!
> I have two minor requests:
> 
>     1. my experience with linters is whenever a new version is released, new warnings/errors begins to pop. Would it be possible to pin cppcheck to a specific version?
> 
>     2. I would like to have a `make cppcheck` target which contains all the needed options, instead of passing a zillion of options from `azure-pipelines.yml`: it makes it much easier to run the linter locally if you want to.
> 
> 
> Moreover, you should probably rebase/merge on top of the current master: now that #73 has been merged, the check should pass.

**Comment by thedrow** [comment]
There are still some style issues and warning we can disable if we wish to do so.

@antocuni Can you please review the output and instruct me what you'd like me to do next?

**Comment by antocuni** [comment]
I think we should turn off style warnings for now, and maybe re-enable them later in another PR where we can discuss which style checks we want to enforce.
If I am correct, if we turn off style warnings and merge #76 , the only issues left are [these](https://dev.azure.com/pyhandle/hpy/_build/results?buildId=507&view=logs&j=71490d96-a242-5f1c-bb38-546ccf5abc39&t=ec6d7519-ab36-52ba-1997-c4da8374ebbc&l=117):
```
hpy/universal/src/handles.c:90:5: portability: %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'intptr_t {aka signed long}'. [invalidPrintfArgType_sint]
    hpy_assert(h._i >= 0 && h._i < h_num_allocated,
    ^
hpy/universal/src/handles.c:99:5: portability: %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'intptr_t {aka signed long}'. [invalidPrintfArgType_sint]
    hpy_assert((((Py_ssize_t)result) & 1) == 0,
    ^
hpy/universal/src/handles.c:102:5: portability: %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'intptr_t {aka signed long}'. [invalidPrintfArgType_sint]
    hpy_assert(result != NULL,
    ^
hpy/universal/src/handles.c:104:5: portability: %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'intptr_t {aka signed long}'. [invalidPrintfArgType_sint]
    hpy_assert(Py_REFCNT(result) > 0,
    ^
hpy/universal/src/handles.c:120:5: portability: %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'intptr_t {aka signed long}'. [invalidPrintfArgType_sint]
    hpy_assert(Py_REFCNT(old) > 0,
```

They look easy to fix, but again I'd like @arigo 's input since he is the author of that code.

**Comment by thedrow** [comment]
> I think we should turn off style warnings for now, and maybe re-enable them later in another PR where we can discuss which style checks we want to enforce.

I honestly don't have an opinion here.

> If I am correct, if we turn off style warnings and merge #76 , the only issues left are [these](https://dev.azure.com/pyhandle/hpy/_build/results?buildId=507&view=logs&j=71490d96-a242-5f1c-bb38-546ccf5abc39&t=ec6d7519-ab36-52ba-1997-c4da8374ebbc&l=117):

Correct.

**Comment by arigo** [comment]
>     hpy_assert(h._i >= 0 && h._i < h_num_allocated,

I guess we need to cast the HPy ``_i`` field to a ``ssize_t``.  Or we could use ``%p`` and cast ``_i`` to a ``void *``.

**Comment by antocuni** [comment]
> I guess we need to cast the HPy _i field (in the next line) to a ssize_t. Or we could use %p and cast _i to a void *.

@thedrow if you fix this, I'll be happy to merge the branch

**Comment by thedrow** [comment]
Wait there are still [problems](https://dev.azure.com/pyhandle/hpy/_build/results?buildId=519&view=logs&j=71490d96-a242-5f1c-bb38-546ccf5abc39&t=ec6d7519-ab36-52ba-1997-c4da8374ebbc&l=14).
I just don't understand why though.

**Comment by thedrow** [comment]
> > I guess we need to cast the HPy _i field (in the next line) to a ssize_t. Or we could use %p and cast _i to a void *.
> 
> @thedrow if you fix this, I'll be happy to merge the branch

Could you? I've invested a lot of time in these PRs already.

**Comment by arigo** [comment]
@thedrow, @antocuni Fixed `hpy_assert()` in `master`.

**Comment by antocuni** [comment]
cool, thank you.
@thedrow could you please rebase/merge on top on the current master to check that the build passes?
I don't think I can do it since I don't have permissions to commit to your fork, I suppose.

**Comment by thedrow** [comment]
Really? I allowed edits by maintainers.
Anyway, done.

**Comment by thedrow** [comment]
The build failed because of the CI cache?
Can you please restart it? Just to make sure it's not something I did.

**Comment by antocuni** [comment]
done. Now `CPPCheck` passes, but we get a cache miss error in the post-build step. I don't really have no idea of what's happening :(

**Pull request merged**
